### ISSUE TITLE
Fix samples format

### ISSUE THREAD

**Issue by chingor13** [googleapis/java-monitoring#231]
Some of the samples migrated from GoogleCloudPlatform/java-docs-samples do not follow the samples guidelines.

**Comment by suraj-qlogic** [comment]
@chingor13 ,I have just split and add **AlertPolicyServiceClient,MetricServiceClient** sample.Here some other client like **GroupServiceClient,ServiceMonitoringServiceClient,NotificationChannelServiceClient** is also available which sample does not available,So can i add below client sample.

- [NotificationChannelServiceClient](https://cloud.google.com/monitoring/api/ref_v3/rpc#google.monitoring.v3.notificationchannelservice)

- [GroupServiceClient](https://cloud.google.com/monitoring/api/ref_v3/rpc#google.monitoring.v3.groupservice)

- [ServiceMonitoringServiceClient](https://cloud.google.com/monitoring/api/ref_v3/rpc#google.monitoring.v3.servicemonitoringservice)

**Comment by suraj-qlogic** [comment]
@chingor13 ,PTAL
